###############################################################################
#                         Docker Compose Nurul H                              #
###############################################################################
version: "3.9"
services:

  db:
    image: postgres:9.6-alpine
    container_name: assets-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DB-Assets
    volumes:
      - ./restore-db/datacenter.sql:/docker-entrypoint-initdb.d/datacenter.sql:ro
    ports:
      - "1029:5432"
    networks:
      - webnet
    restart: unless-stopped

  webserver:
    image: nginx:alpine
    container_name: webserver
    depends_on:
      - db
      - php-fpm
    working_dir: /application
    volumes:
      - ./application:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "1028:80"
    networks:
      - webnet
    restart: unless-stopped

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /application
    volumes:
      - ./application:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
